name: Spamm
main: me.skyrimfan1.spamm.Spamm
version: 1.0.1
description: Prevents those darn client spammers!
author: skyrimfan1
commands:
  spamm:
    description: The generic Spamm command
permissions:
  spamm.exempt:
    description: Allows a user to bypass Spamm
    default: op
  spamm.update:
    description: Allows an admin (or player) to update Spamm
    default: op


  